export const CODE_TO_DOMAIN_DATA = [
    "QSA016;Automates",
    "CDP016;Perf globale CTRL PROD CAISSE",
    "QHR016;Qualité des Horaires Réseau",
    "SMA016;Numérique",
    "ENC016;Gestion du Fiduciaire",
    "GDS016;Perf globale Logistique-Appro",
    "GDR016;Perf globale Courrier-Colis"
];

export const CODE_TO_INDICATOR_DATA = [
    "I0645;Automates bancaires",
    "I0646;Automates Courrier-Colis",
    "I0647;Automates",
    "I0648;Automates Nabanco",
    "I0660;Erreurs de caisse",
    "I0675;Validation situation de caisse J à J+1",
    "I0678;Fichier d'échange",
    "I0679;Perf globale Contrôle de production Caisse",
    "I0680;Qualité des pièces justificatives",
    "I0684;Qualité des Horaires Réseau",
    "I0691;Utilisation Smarteo au dépôt",
    "I0692;Utilisation Smarteo au retrait",
    "I0693;Performance Globale Numérique",
    "I0973;Utilisation Smarteo à la vente",
    "I0696;Rotation du stock d'encaisse",
    "I0697;Gestion du fiduciaire",
    "NOT01_ACO;Couverture de stock Produits",
    "NOT02_ACO;Respect plan de livraison",
    "NOT06_ACO;Perf globale Logistique-Appro",
    "NOT08_ACO;Respect délai réception livraisons DAPO",
    "NOT09_ACO;Démarque",
    "NOTE_ARR_GDR_ACO;Flashage arrivée d'instance",
    "NOTE_CPT_SIG_ACO;Capture de Signature",
    "NOTE_GDR_ACO;Perf globale Courrier-Colis",
    "NOTE_LEV_GDR_ACO;Flashage Levée d'instance",
];
