export const ENTITIES_DATA = [
    {
        CodeRegate: 132340,
        CodeBureau: "02121A",
        LibelleBureau: "MARSEILLE DEX RLP SUD EST",
        CodeDex: "02121A",
        LibelleDex: "MARSEILLE DEX RLP SUD EST",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 63410,
        CodeBureau: "82427A",
        LibelleBureau: "NICE 04 05 06 83 DR",
        CodeDex: "02121A",
        LibelleDex: "MARSEILLE DEX RLP SUD EST",
        CodeDr: "82427A",
        LibelleDr: "NICE 04 05 06 83 DR",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 61790,
        CodeBureau: "00883A",
        LibelleBureau: "NICE DT NICE BAIE DES ANGES",
        CodeDex: "02121A",
        LibelleDex: "MARSEILLE DEX RLP SUD EST",
        CodeDr: "82427A",
        LibelleDr: "NICE 04 05 06 83 DR",
        CodeDt: "00883A",
        LibelleDt: "NICE DT NICE BAIE DES ANGES",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 62200,
        CodeBureau: "00913A",
        LibelleBureau: "NICE DT NICE VALLEES D AZUR",
        CodeDex: "02121A",
        LibelleDex: "MARSEILLE DEX RLP SUD EST",
        CodeDr: "82427A",
        LibelleDr: "NICE 04 05 06 83 DR",
        CodeDt: "00913A",
        LibelleDt: "NICE DT NICE VALLEES D AZUR",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
/* 
    {
        CodeRegate: 209970,
        CodeBureau: "03517A",
        LibelleBureau: "AJACCIO DPC",
        CodeDex: "03517A",
        LibelleDex: "AJACCIO DPC",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
*/    
    {
        CodeRegate: 335990,
        CodeBureau: "06070A",
        LibelleBureau: "BORDEAUX DEX RLP GRAND SUD OUEST",
        CodeDex: "06070A",
        LibelleDex: "BORDEAUX DEX RLP GRAND SUD OUEST",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 941710,
        CodeBureau: "17377A",
        LibelleBureau: "GENTILLY DEX OM",
        CodeDex: "17377A",
        LibelleDex: "GENTILLY DEX OM",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 354090,
        CodeBureau: "55526A",
        LibelleBureau: "RENNES DEX RLP OUEST",
        CodeDex: "55526A",
        LibelleDex: "RENNES DEX RLP OUEST",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 356620,
        CodeBureau: "12079D",
        LibelleBureau: "RENNES 22 29 35 56 DR",
        CodeDex: "55526A",
        LibelleDex: "RENNES DEX RLP OUEST",
        CodeDr: "12079D",
        LibelleDr: "RENNES 22 29 35 56 DR",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 352860,
        CodeBureau: "06610A",
        LibelleBureau: "RENNES DT METROPOLE",
        CodeDex: "55526A",
        LibelleDex: "RENNES DEX RLP OUEST",
        CodeDr: "12079D",
        LibelleDr: "RENNES 22 29 35 56 DR",
        CodeDt: "06610A",
        LibelleDt: "RENNES DT METROPOLE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 562670,
        CodeBureau: "10255A",
        LibelleBureau: "VANNES DT D ORIENT",
        CodeDex: "55526A",
        LibelleDex: "RENNES DEX RLP OUEST",
        CodeDr: "12079D",
        LibelleDr: "RENNES 22 29 35 56 DR",
        CodeDt: "10255A",
        LibelleDt: "VANNES DT D ORIENT",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },
    {
        CodeRegate: 595350,
        CodeBureau: "55527A",
        LibelleBureau: "LILLE DEX RLP NORD EST",
        CodeDex: "55527A",
        LibelleDex: "LILLE DEX RLP NORD EST",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    },  
    {
        CodeRegate: 758520,
        CodeBureau: "55530A",
        LibelleBureau: "PARIS DEX RLP ILE DE FRANCE",
        CodeDex: "55530A",
        LibelleDex: "PARIS DEX RLP ILE DE FRANCE",
        CodeDr: "-1",
        LibelleDr: "NON RENSEIGNE",
        CodeDt: "-1",
        LibelleDt: "NON RENSEIGNE",
        CodeSecteur: "-1",
        LibelleSecteur: "NON RENSEIGNE"
    }
];